### ISSUE TITLE
AppCompatActivity找不到, v4包和v7包兼容问题

### ISSUE THREAD

**Issue by LinTaoAndroid** [haibuzou/Calendar365#1]
这个效果确实不错,但是我把项目移植到我的项目中(eclipse开发)中,发现v7包里的AppCompatActivity这个类在mainactivity里一直找不到,项目中不报错,但是每当我点击mainactivity的时候就提示AppCompatActivity这个类找不到,不知道在as中是不是也有这样的问题!
关于这个类找不到的问题,我想尽一切办法,耗费了3天的时间还是没能够解决!

**Comment by haibuzou** [comment]
@OpenSourceMIUI  AS项目中AppCompatActivity 是做了 compile 'com.android.support:appcompat-v7:23.2.0' 依赖
在ec中可以不使用appcompat-v7的资源，不去继承AppCompatActivit 只继承Activity，同时styles.xml文件中的主题要修改 Theme.AppCompat.NoActionBar 为你现在的可以用的主题

**Comment by LinTaoAndroid** [comment]
嗯嗯,非常感谢,这个问题解决了!
