### ISSUE TITLE
怎么返回当天的日期，还有给指定的时间加角标

### ISSUE THREAD

**Issue by jiaxin11** [haibuzou/Calendar365#10]
看了半天代码，有点乱。请撸主帮忙。

**Comment by haibuzou** [comment]
@jiaxin11 绘画日历的关键类是 MonthView和WeekView一个是画月，一个是画周，2者的实现是一样的。可以从MonthView的draw方法开始看。drawBG**的方法都是用来画背景的处理，drawGregorian用来画日期的文字，drawFestival日期下方的节日。日期是通过传入指定的日期范围，通过DPCManager的obtainDPInfo方法来生成。 总之从onDraw开始一步步跟就可以了，日期的数据生成和判断日期的关键包是calendar下的calendars包下面的DpManager，绘制的关键包是View下的MonthView，集中在这2个就可以了
